FROM debian:stretch

RUN apt-get update && apt-get install -y openvpn zip

RUN make-cadir /root/ca

WORKDIR /root/ca

RUN ln -s openssl-1.0.0.cnf openssl.cnf

COPY files/ca /root/files/

COPY bin/ca/ /usr/local/bin/
RUN chmod a+x /usr/local/bin/*
