FROM debian:stretch

RUN apt-get update && apt-get install -y openvpn net-tools

ADD bin/ /usr/local/bin
RUN chmod a+x /usr/local/bin/*

# Internally uses port 1194/udp, remap using `docker run -p 443:1194/tcp`
EXPOSE 1194/udp
