FROM alpine:latest

# Install openresolv to be able to modify /etc/resolv.conf
RUN apk add --no-cache openvpn openresolv

COPY bin/client/ /usr/local/bin/
RUN chmod a+x /usr/local/bin/*

CMD ["start-client"]
